[Fix] Snap Dto 통합 #116
AppCenter-Snaptime/snaptime-springboot pull request #117
Opened 2024-07-20 15:22 UTC by NARUBROWN

## 📋 이슈 번호
close #116 
## 🛠 구현 사항
SnapPagingInfo -> SnapResInfo로 이름 변경하였음
FindSnapResDto -> AlbumSnapResDto로 이름 변경하였음
## 📚 기타

2024-07-20 21:55 UTC, parseyong requested changes

2024-07-20 21:55 UTC, parseyong commented on src/main/java/me/snaptime/friend/controller/FriendController.java
> +            @Parameter(name = "targetLoginId" , description = "친구목록을 조회할 유저의 writerLoginId", required = true,example = "tempLoginId"),
인텔리제이 refactor기능 이용하면 자주 이러는데 loginId 변수명 바뀔 때 다른 코드의 loginId도 같이 바뀐거같아요. 다른 부분도 많이 바뀐거같아서 변경기록보고 수정해야할거같아요

2024-07-20 21:55 UTC, parseyong commented on src/main/java/me/snaptime/snap/dto/res/AlbumSnapResDto.java
> +public record AlbumSnapResDto(
스냅dto를 하나로 합치는거면 둘중에 dto하나는 나중에 삭제하는건가요?

2024-07-20 21:55 UTC, parseyong commented on src/main/java/me/snaptime/snap/dto/res/AlbumSnapResDto.java
>          }
스냅에 연결된 유저가 null인 경우는 없어서 이부분은 불필요한거같습니다.

2024-07-20 21:55 UTC, parseyong commented on src/main/java/me/snaptime/snap/dto/res/SnapResInfo.java
>  }
지금 똑같은 정적메소드가 두개생성된거같아요.

2024-07-21 05:54 UTC, NARUBROWN commented on src/main/java/me/snaptime/friend/controller/FriendController.java
> +            @Parameter(name = "targetLoginId" , description = "친구목록을 조회할 유저의 writerLoginId", required = true,example = "tempLoginId"),
이런.. 그냥 close 하고 처음부터 다시 수정해야겠네

2024-07-21 05:55 UTC, NARUBROWN commented on src/main/java/me/snaptime/snap/dto/res/AlbumSnapResDto.java
> +public record AlbumSnapResDto(
아니야 하나는 앨범 전체 조회시 조회되는 Dto로 남게 될거야

2024-07-21 05:55 UTC, NARUBROWN commented on src/main/java/me/snaptime/snap/dto/res/AlbumSnapResDto.java
>          }
그러네! 수정하도록 할게

2024-07-21 05:56 UTC, NARUBROWN commented on src/main/java/me/snaptime/snap/dto/res/SnapResInfo.java
>  }
아니야 첫번째 매개변수가 달라

2024-07-21 05:56 UTC, closed without merging