[Feat] 스프링 시큐리티 추가
AppCenter-Snaptime/snaptime-springboot pull request #27
Opened 2024-02-26 13:40 UTC by sukangpunch

## 📋 이슈 번호
close #25 
## 🛠 구현 사항
1.  Spring Security 구현, jwt 기반 인증방식 구현
2. 로그인 관련 Service, controller 메서드, dto 추가
3. 로그 출력 설정 파일 추가
## 📚 기타

2024-02-27 00:55 UTC, NARUBROWN requested changes
모든 Test를 주석처리 해놨네! @WithMockUser를 사용하면 정상적으로 테스트가 진행되니 참고해서 코드를 수정해줘

2024-02-27 00:55 UTC, NARUBROWN commented on src/main/java/me/snaptime/user/data/domain/User.java
> +        this.roles = roles;
id가 대문자로 되어있네 수정부탁해!

2024-02-27 02:51 UTC, sukangpunch commented on src/main/java/me/snaptime/user/data/domain/User.java
> +        this.roles = roles;
수정할게!!

2024-02-27 02:51 UTC, sukangpunch commented
> 모든 Test를 주석처리 해놨네! @WithMockUser를 사용하면 정상적으로 테스트가 진행되니 참고해서 코드를 수정해줘

오케이 !! 수정할게

2024-02-27 05:49 UTC, parseyong commented on src/main/java/me/snaptime/user/data/domain/User.java
> +        this.roles = roles;
빌더에 id필드를 노출 안시키는 방향으로 수정하면 좋을거같아요

2024-02-27 05:53 UTC, parseyong reviewed
PasswordEncodeConfig랑 SecurityConfig클래스는 다른 config클래스랑 같은 위치에 두는게 config파일 관리하는데 편할거 같아요

Jwt관련 로직은 config패키지 안에 두는것보단 common패키지 안에 새로운 패키지를 만들어서 관리하는건 어떤가요?

2024-02-27 05:57 UTC, parseyong requested changes
user정보 삭제,수정,조회연산에서 jwt토큰의 인증정보를 통해 자신의 user정보를 삭제,수정,조회하는지 검증하는 로직이 필요해 보입니다. 현재로직은 Req보낼때 다른사람의 userId값을 보내면 다른사람이 자신의 user정보를 삭제할 수 있어서

2024-02-27 05:59 UTC, sukangpunch commented
> PasswordEncodeConfig랑 SecurityConfig클래스는 다른 config클래스랑 같은 위치에 두는게 config파일 관리하는데 편할거 같아요
> 
> Jwt관련 로직은 config패키지 안에 두는것보단 common패키지 안에 새로운 패키지를 만들어서 관리하는건 어떤가요?

common.config -> SecurityConfig, PasswordEncodeConfig
common.jwt-> jwtAuthenticationFilter, JwtProvider 이런식으로 말인가요?

2024-02-27 06:02 UTC, sukangpunch commented
> user정보 삭제,수정,조회연산에서 jwt토큰의 인증정보를 통해 자신의 user정보를 삭제,수정,조회하는지 검증하는 로직이 필요해 보입니다. 현재로직은 Req보낼때 다른사람의 userId값을 보내면 다른사람이 자신의 user정보를 삭제할 수 있어서

토큰에서 정보를 빼내 crud를 구현하는 방향으로 해볼게염

2024-02-27 06:19 UTC, sukangpunch commented on src/main/java/me/snaptime/user/data/domain/User.java
> +        this.roles = roles;
빌더에 id 필드를 제외하면 유저 빌더 사용하는 모든 Test코드를 수정 해야 하는데 괜찮나요?

2024-02-27 07:09 UTC, parseyong commented on src/main/java/me/snaptime/user/data/domain/User.java
> +        this.roles = roles;
spy객체로 getId메소드를 stubbing하시면 됩니다. user객체를 만들때 꼭 userId값을 넣지 않아도 생성할 수있어요

2024-02-27 12:11 UTC, sukangpunch commented on src/main/java/me/snaptime/user/data/domain/User.java
> +        this.roles = roles;
알겠습니다!

2024-03-02 13:33 UTC, parseyong approved these changes

2024-03-02 13:48 UTC, NARUBROWN approved these changes

2024-03-02 15:02 UTC, merged