[Feat] 유저 프로필 화면을 위한 query작성 - #30
AppCenter-Snaptime/snaptime-springboot pull request #35
Opened 2024-03-15 06:36 UTC by sukangpunch

## 📋 이슈 번호
close #30 
## 🛠 구현 사항
피그마에 그려져 있는 유저 프로필 화면을 구성하기 위해,
1. (유저이름 + 프로필 사진 id), (유저 앨범 이름과 id + 앨범당 최근 스냅 id 2개) 에 해당하는 queryDSL문을 작성.
2. UserService, UserController 에 findAlbumSnap , findUserProfile 메서드 작성.
3. queryDsl 로직을 테스트 하기 위해, 테스트 전용 h2 인메모리 데이터베이스 설정.

## 📚 기타
현재 snap과 photo의 관계 수정에 대한 내용이 main에 존재하지 않아, queryDSL 테스트 코드 작성을 조금 미루겠습니다.
그리고 인메모리 h2 데이터베이스를 사용 관련하여 src/test/resource/application-test.yml 와 같이 프로퍼티를 작성 하였는데,  정확한 원인 파악은 못했지만 src/main/resource/appication.yml 에  mysql 세팅 이슈로, h2에 제대로된 쿼리가 날라가지 않는 듯 해 보입니다.

왜 인지는 모르겠으나, main의 applicaiton.yml 파일에 영향을 받아, mysql설정이 적용된 상태에서 h2에 접근하다가 에러가 발생한 듯 보인다. 그래서 test-app..yml 파일의 우선순위를 높였다.
**@TestPropertySource(properties = {"spring.config.location=classpath:application-test.yml"})**
해당 내용으로 일단 문제를 해결하였습니다.

2024-03-16 08:02 UTC, parseyong reviewed
dto안에 request / response / userprofile1 / userprofile2 디렉토리로 나누어져있는데 이렇게 나눈 이유가 있나요?

2024-03-16 08:25 UTC, parseyong requested changes

2024-03-16 08:25 UTC, parseyong commented on src/main/java/me/snaptime/user/data/repository/impl/UserCustomRepositoryImpl.java
> +        }
album.id, album.name, snap.id 3개의 값을 추출해서 album.id값만 사용하는데 나머지 album.name, snap.id를 가져온 이유가 있나요?

그리고 중복제거는 distinct()를 사용하거나 처음부터 Set으로 받으면 될듯합니다.

2024-03-16 08:25 UTC, parseyong commented on src/main/java/me/snaptime/user/data/repository/impl/UserCustomRepositoryImpl.java
> +        }
맨처음에 실행된 쿼리에서 앨범id를 가져와서 앨범id를 다시 가져올 필요가 없어보입니다. 

그리고 이 쿼리에서는 앨범에 포함된 최신사진 2개를 추출하는 쿼리이기때문에 user테이블과 조인이 필요없어보입니다.

2024-03-16 08:25 UTC, parseyong commented on src/test/java/me/snaptime/user/repository/UserCustomRepositoryTest.java
> +public class UserCustomRepositoryTest {
불필요한 주석이 너무 많은거같아요...

2024-03-16 08:34 UTC, parseyong commented on src/main/java/me/snaptime/user/data/repository/impl/UserCustomRepositoryImpl.java
> +        List<Tuple> tuples1 = jpaQueryFactory
(유저와 연결된 앨범을 가져오는 쿼리 / 각 앨범에 포함된 최신 사진2개 가져오는쿼리) 로 나누어서 처리가 되면 tuple1,tuple2로 받아오는 것 보단 적절한 이름을 부여하는 게 읽는데 더 편할 것 같아요.

2024-03-16 09:53 UTC, sukangpunch commented
> dto안에 request / response / userprofile1 / userprofile2 디렉토리로 나누어져있는데 이렇게 나눈 이유가 있나요?



> dto안에 request / response / userprofile1 / userprofile2 디렉토리로 나누어져있는데 이렇게 나눈 이유가 있나요?

처음에 구현한, 프로필 페이지 로직 내용을 일단 남겨 놓을 생각이었습니다!

2024-03-16 09:56 UTC, sukangpunch commented on src/main/java/me/snaptime/user/data/repository/impl/UserCustomRepositoryImpl.java
> +        }
distinct()를 사용해서 중복을 제거 해 보겠습니다!

2024-03-16 09:57 UTC, sukangpunch commented on src/main/java/me/snaptime/user/data/repository/impl/UserCustomRepositoryImpl.java
> +        }
그러네요! 수정하겠습니다 !

2024-03-16 09:57 UTC, sukangpunch commented on src/test/java/me/snaptime/user/repository/UserCustomRepositoryTest.java
> +public class UserCustomRepositoryTest {
처리하겠습니다!

2024-03-16 09:58 UTC, sukangpunch commented on src/main/java/me/snaptime/user/data/repository/impl/UserCustomRepositoryImpl.java
> +        List<Tuple> tuples1 = jpaQueryFactory
수정하겠습니다!

2024-03-17 11:21 UTC, parseyong approved these changes

2024-03-17 12:36 UTC, NARUBROWN approved these changes

2024-03-18 11:07 UTC, merged