[Fix] 프로필 페이지 조회 메서드 수정
AppCenter-Snaptime/snaptime-springboot pull request #41
Opened 2024-04-02 06:13 UTC by sukangpunch

## 📋 이슈 번호
close #39 
## 🛠 구현 사항
프로필 페이지 조회 시 유저 프로필 사진과 앨범 당 snap 들 과 같이 파일 형식의 데이터를 조회할 때, 해당 파일의 위치를 가지고 있는 객체의 id 값을 리턴 하는 구조에서, 해당 resource의 url을 리턴 하는 구조로 수정하였습니다.
## 📚 기타

2024-04-02 06:25 UTC, parseyong requested changes

2024-04-02 06:25 UTC, parseyong commented on src/main/java/me/snaptime/user/service/UserService.java
> +    }
유저탈퇴할 떄 토큰에서 loginId정보와 요청받은 loginId값을 비교해서 삭제권한을 확인하는게좋을거같아요. A유저가 B유저의 loginId를 보내면 B유저는 회원탈퇴를 하지 않아도 회원이 탈퇴될 수 있을것같아요

2024-04-02 06:25 UTC, parseyong commented on src/main/java/me/snaptime/user/service/UserService.java
> +        }
유저탈퇴와 마찬가지로 수정권한을 확인하는게 좋을거같아요

2024-04-02 06:27 UTC, parseyong commented
유저정보 조회할 때 비밀번호는 보내주지 않는게 좋을거같네요. 그리고 유저 프로필조회할 때 팔로잉/팔로우 수를 반환하는 로직은 아직 구현안하신건가요?

2024-04-02 06:37 UTC, sukangpunch commented on src/main/java/me/snaptime/user/service/UserService.java
> +        }
확인입니다!

2024-04-02 06:37 UTC, sukangpunch commented on src/main/java/me/snaptime/user/service/UserService.java
> +    }
> 유저탈퇴할 떄 토큰에서 loginId정보와 요청받은 loginId값을 비교해서 삭제권한을 확인하는게좋을거같아요. A유저가 B유저의 loginId를 보내면 B유저는 회원탈퇴를 하지 않아도 회원이 탈퇴될 수 있을것같아요

확인입니당!

2024-04-02 06:38 UTC, sukangpunch commented
> 유저정보 조회할 때 비밀번호는 보내주지 않는게 좋을거같네요. 그리고 유저 프로필조회할 때 팔로잉/팔로우 수를 반환하는 로직은 아직 구현안하신건가요?



> 유저정보 조회할 때 비밀번호는 보내주지 않는게 좋을거같네요. 그리고 유저 프로필조회할 때 팔로잉/팔로우 수를 반환하는 로직은 아직 구현안하신건가요?



> 유저정보 조회할 때 비밀번호는 보내주지 않는게 좋을거같네요. 그리고 유저 프로필조회할 때 팔로잉/팔로우 수를 반환하는 로직은 아직 구현안하신건가요?

이미 following, follower cnt 반환 로직이 있는줄 착각하고 있었네! 만들겠음니당

2024-04-10 10:57 UTC, NARUBROWN approved these changes

2024-04-10 11:12 UTC, parseyong approved these changes

2024-04-10 11:23 UTC, merged